spring:
  datasource:
    url: jdbc:postgresql://subscription-postgresql:5432/subscriptiondb
    username: subscriptionUser
    password: subscriptionPass
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create
      
server:
  port: 8080
                
subscriptionService:
    security:
        userName: user
        password: password
    url: http://subscription-service:8080
    path: /subscription
