spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/subscriptiondb
        username: subscriptionUser
        password: subscriptionPass
        driverClassName: org.postgresql.Driver
    jpa:
        database: POSTGRESQL
        show-sql: false
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true
                sql_comments: true
                format_sql: true
                
subscriptionService:
    security:
        userName: user
        password: password
    url: http://localhost:8884
    path: /subscription
